name: nextstrain-prot-titers-tree

channels:
  - conda-forge
  - bioconda

dependencies:
  - black
  - augur=33.0.1
  - pandas=2.3
  - pyarrow
  - python=3.13
  - snakefmt
  - snakemake=9.19
  - ruff
