name: nextstrain-prot-titers-tree

channels:
  - conda-forge
  - bioconda

dependencies:
  - black
  - augur=32.1.0
  - pandas=2.3
  - pyarrow
  - python=3.13
  - snakefmt
  - snakemake=9.14
  - ruff
