# Example configuration file for `nexstrain-prot-titers-tree`

# FASTA file with aligned protein sequences with titer measurements
alignment: example_data/alignment.fa

# FASTA file with single outgroup sequence, must already be aligned to rest of alignment
outgroup: example_data/outgroup.fa

# Map sites in alignment to numbering used in mutation naming. Should be a TSV
# with three columns:
#  - sequential_site: sequential 1, 2, ... numbering of alignment
#  - protein: name of the protein (eg, HA1, HA2)
#  - protein_site: number of mutation in protein
site_numbering_map: example_data/site_numbering_map.tsv

# TSV file with metadata on strains in alignment (not outgroup).
# Must have column "strain" matching the sequence names in alignment,
# and a column "date" with the numerical date (eg, 2025.5). Must also have
# the additional columns specified in `color_by_metadata`.
metadata: example_data/metadata.tsv

# Columns in `metadata` that we include in the tree to enable it to
# be colored by them (do not include 'strain' or 'date'). Each key
# is a column name, and it defines a mapping that can optionally
# include any of the following keys:
#   - scale_type: "viridis_linear", "viridis_log", "viridis_r_linear", "viridis_r_log"
#   - fixed_min: number giving fixed minimum of scale; else determined from data
#   - fixed_max: number giving fixed maximum of scale; else determined from data
#   - exclude_auto_scale: list strains to exclude when calculating auto limits
color_by_metadata:
  strain_type: {}
  subclade: {}
  median_titer_All_sera:
    scale_type: viridis_r_log
  median_titer_EPIHK_sera:
    scale_type: viridis_r_log
  median_titer_NIID_sera:
    scale_type: viridis_r_log
  median_titer_SCH_sera:
    scale_type: viridis_r_log
  median_titer_UWMC_sera:
    scale_type: viridis_r_log
    exclude_auto_scale: [A/Maldives/2147/2024]  # just an example of setting lims excluding extreme strain
  frac_w_titer_below_140_All_sera:
    scale_type: viridis_linear
  frac_w_titer_below_140_EPIHK_sera:
    scale_type: viridis_linear
  frac_w_titer_below_140_NIID_sera:
    scale_type: viridis_linear
  frac_w_titer_below_140_SCH_sera:
    scale_type: viridis_linear
  frac_w_titer_below_140_UWMC_sera:
    scale_type: viridis_linear
    fixed_max: 1  # just an example of fixing upper limit to scale

# Do we display per-serum titers in measurement panel? If yes, specify dict similar to
# below; if no then set titers to null.
titers:
  titers_tsv: example_data/titers.tsv  # TSV with titers, must have columns "strain" and "serum"
  titer_col: log2_titer  # column in titers_tsv with the titers
  grouping_columns:  # list additional columns in titers_tsv by which titers can be grouped
    - group
    - collection_date_numerical
    - age_years
    - sex
  addtl_args:  # additional arguments that can be passed to `augur measurements export`
    title: serum neutralizing titers  # title for measurements panel
    x-axis-label: log2 titer  # x-axis label
    measurements-display: raw

# display defaults for auspice configuration, or set to {} if you do
# not want to set any defaults. See:
# https://docs.nextstrain.org/projects/auspice/en/v2.47.0/advanced-functionality/view-settings.html
display_defaults:
  color_by: median_titer_All_sera
  distance_measure: div
  branch_label: aa

# results generated by pipeline go in this directory
results_subdir: example_results

# Final auspice JSON goes here. Note that if you want to be able to look at the tree via
# a Nextstrain Community Build, you should following the naming convention described here:
# https://docs.nextstrain.org/en/latest/guides/share/community-builds.html
auspice_json: auspice/nextstrain-prot-titers-tree.json

# additional arguments to augur export v2; all of these are optional, set to empty dict
# of {} of no additional arguments
addtl_export_args:
  title: Example tree for nextstrain-prot-titers-tree showing human neutralizing antibody titers to H3N2 influenza viruses as of summer of 2025
  maintainers: Jesse Bloom <https://jbloomlab.org/>
  build-url: https://github.com/jbloomlab/nextstrain-prot-titers-tree
