[project]
name = "nextstrain-prot-titers-tree"
version = "1.5.1"
description = "Build interactive nextstrain trees on protein sequences designed to display neutralization titer values"
readme = "README.md"
license = {text = "MIT"}
authors = [
    {name = "Bloom Lab", email = "jbloom@fredhutch.org"}
]
requires-python = ">=3.9"

[project.urls]
Repository = "https://github.com/jbloomlab/nextstrain-prot-titers-tree"

[tool.black]
target-version = ["py313"]

[tool.ruff]
builtins = [
    "snakemake",  # may appear undefined as passed to scripts via `Snakefile`
]
