"""``snakemake`` file for ``nextstrain-prot-titers-tree``."""

import os.path
import re
import shlex

# get some variables from config
results_subdir = config["results_subdir"]
log_subdir = os.path.join(results_subdir, "logs")
outgroup = config["outgroup"]
no_outgroup = (outgroup is None) or (outgroup == "null")
# optional so that configurations written before this key existed keep working, and
# because the value it defaults to is the one nearly every tree wants
set_branch_lengths_to_n_mutations = config.get(
    "set_branch_lengths_to_n_mutations", True
)

# `color_by_metadata` can be specified inline in the configuration and/or in a YAML
# file (`color_by_metadata_file`, useful when the columns are generated by a pipeline
# rather than written by hand). The two are merged and validated at run time by
# `resolve_color_by_metadata`, since the file may not exist when this file is parsed.
# The key is optional, as a project need not have such a file.
color_by_metadata_file = config.get("color_by_metadata_file")
if color_by_metadata_file == "null":
    color_by_metadata_file = None

# `titers` is null, a single collection (mapping), or a list of collections; normalize
# to a list. Each collection becomes one collection in the measurements panel.
titers = config["titers"]
if titers == "null":
    titers = None
if titers is None:
    titer_collections = []
elif isinstance(titers, dict):
    titer_collections = [titers]
elif isinstance(titers, list):
    if not titers:
        raise ValueError("`titers` is an empty list; use null for no titers")
    titer_collections = titers
else:
    raise ValueError(f"invalid `titers` of type {type(titers).__name__}: {titers}")

# collections are keyed for the measurements panel and for file names; `key` is required
# when there is more than one collection, as it is what distinguishes them
req_titer_keys = {"titers_tsv", "titer_col", "grouping_columns", "addtl_args"}
titer_collection_keys = []
for collection in titer_collections:
    if not isinstance(collection, dict):
        raise ValueError(f"`titers` collection is not a mapping: {collection}")
    missing_keys = sorted(req_titer_keys - set(collection))
    if missing_keys:
        raise ValueError(f"`titers` collection lacks {missing_keys}: {collection}")
    if "key" in collection:
        titer_collection_keys.append(str(collection["key"]))
    elif len(titer_collections) == 1:
        titer_collection_keys.append("titers")
    else:
        raise ValueError(
            "each `titers` collection needs a 'key' when there is more than one "
            f"collection, but this one has none: {collection}"
        )
if len(set(titer_collection_keys)) != len(titer_collection_keys):
    raise ValueError(f"duplicate `titers` collection keys: {titer_collection_keys}")
# keys name files and are passed to `augur measurements export` as shell words
keys_w_space = [key for key in titer_collection_keys if len(key.split()) != 1]
if keys_w_space:
    raise ValueError(
        f"`titers` collection keys cannot contain whitespace: {keys_w_space}"
    )

# the collection displayed when the measurements panel is opened; if not specified,
# `augur measurements concat` displays the first collection
default_collections = [
    key
    for (key, collection) in zip(titer_collection_keys, titer_collections)
    if collection.get("default", False)
]
if len(default_collections) > 1:
    raise ValueError(
        f"only one `titers` collection can have 'default: true': {default_collections}"
    )
default_collection = default_collections[0] if default_collections else None

titer_collection_d = dict(zip(titer_collection_keys, titer_collections))

# sanitized titers keep their historical name when there is just one collection
sanitized_titers = {
    key: os.path.join(
        results_subdir,
        "titers.tsv" if len(titer_collection_keys) == 1 else f"titers_{key}.tsv",
    )
    for key in titer_collection_keys
}

# if we are getting titers, they are stored in file similar to the
# auspice_json but with _measurements suffix as a sidecar JSON
auspice_json = config["auspice_json"]
auspice_titers_json = os.path.splitext(auspice_json)[0] + "_measurements.json"


wildcard_constraints:
    collection="|".join(re.escape(key) for key in titer_collection_keys) or r"$^",


rule all:
    input:
        ([auspice_json, auspice_titers_json] if titer_collections else [auspice_json]),


rule resolve_color_by_metadata:
    """Merge inline `color_by_metadata` with `color_by_metadata_file` and validate.

    Writes the merged specification for the rules that color the tree, and the
    corresponding `augur export v2` arguments for the `export` rule (which needs them
    at run time, as the file is not necessarily present when the pipeline is parsed).

    """
    input:
        **(
            {"color_by_metadata_file": color_by_metadata_file}
            if color_by_metadata_file
            else {}
        ),
    output:
        resolved=os.path.join(results_subdir, "resolved_color_by_metadata.yml"),
        export_args=os.path.join(results_subdir, "export_metadata_args.txt"),
    log:
        os.path.join(log_subdir, "resolve_color_by_metadata.txt"),
    conda:
        "environment.yml"
    params:
        # both keys are optional, and `or` also covers writing one as an explicit null;
        # this is the only place their defaults are applied
        color_by_metadata=config.get("color_by_metadata") or {},
        metadata_columns=config.get("metadata_columns") or [],
        has_file=bool(color_by_metadata_file),
    script:
        "scripts/resolve_color_by_metadata.py"


rule prep_and_sanitize_data:
    """Prep alignment and remove special characters from strain names."""
    input:
        # titers are lists over the collections, in the order of `titer_collection_keys`
        **(
            {"titers": [c["titers_tsv"] for c in titer_collections]}
            if titer_collections
            else {}
        ),
        **({} if no_outgroup else {"outgroup": outgroup}),
        alignment=config["alignment"],
        metadata=config["metadata"],
        resolved_color_by_metadata=rules.resolve_color_by_metadata.output.resolved,
    output:
        **(
            {"titers": [sanitized_titers[key] for key in titer_collection_keys]}
            if titer_collections
            else {}
        ),
        alignment=os.path.join(results_subdir, "alignment_w_outgroup.fa"),
        metadata=os.path.join(results_subdir, "metadata.tsv"),
    log:
        os.path.join(log_subdir, "prep_and_sanitize_data.txt"),
    conda:
        "environment.yml"
    params:
        titer_cols=[
            [
                "strain",
                "serum",
                collection["titer_col"],
                *[
                    c
                    for c in collection["grouping_columns"]
                    if c not in {"strain", "serum", collection["titer_col"]}
                ],
            ]
            for collection in titer_collections
        ],
        titer_collection_keys=titer_collection_keys,
        no_outgroup=no_outgroup,
    script:
        "scripts/prep_and_sanitize_data.py"


rule tree:
    """Build tree using Poisson model that weights all amino-acid mutations equally."""
    input:
        alignment=rules.prep_and_sanitize_data.output.alignment,
    output:
        outdir=directory(os.path.join(results_subdir, "iqtree")),
        raw_tree=os.path.join(results_subdir, "raw_tree.nwk"),
    log:
        os.path.join(log_subdir, "tree.txt"),
    conda:
        "environment.yml"
    threads: 8
    params:
        prefix=lambda _, output: os.path.join(output.outdir, "tree"),
    shell:
        """
        mkdir -p {output.outdir} &>{log}
        iqtree \
            -s {input.alignment} \
            --seqtype AA \
            -m Poisson \
            -fast \
            --seed 1 \
            -T {threads} \
            --prefix {params.prefix} \
            &>>{log}
        cp {params.prefix}.treefile {output.raw_tree} &>>{log}
        """


rule treetime:
    """Use `treetime` to refine tree and get ancestral states / inferred mutations.

    We use `treetime` directly rather than `augur refine` and `augur ancestral` in
    order to be able to process amino-acid sequences, with the custom gap-aware
    Poisson GTR model that the README describes.
    """
    input:
        raw_tree=rules.tree.output.raw_tree,
        metadata=rules.prep_and_sanitize_data.output.metadata,
        alignment=rules.prep_and_sanitize_data.output.alignment,
        custom_gtr=workflow.source_path("data/poisson_gap_aa.txt"),
    output:
        timetree_w_outgroup=os.path.join(results_subdir, "treetime/timetree.nexus"),
        divtree_w_outgroup=os.path.join(
            results_subdir, "treetime/divergence_tree.nexus"
        ),
        ancestral_sequences=os.path.join(
            results_subdir, "treetime/ancestral_sequences.fasta"
        ),
        dates=os.path.join(results_subdir, "treetime/dates.tsv"),
    log:
        os.path.join(log_subdir, "treetime.txt"),
    conda:
        "environment.yml"
    params:
        outdir=lambda _, output: os.path.dirname(output.timetree_w_outgroup),
        reroot="least-squares" if no_outgroup else "outgroup",
    shell:
        """
        treetime \
            --tree {input.raw_tree} \
            --aln {input.alignment} \
            --dates {input.metadata} \
            --name-column strain \
            --date-column date \
            --reroot {params.reroot} \
            --branch-length-mode input \
            --aa \
            --custom-gtr {input.custom_gtr} \
            --rng-seed 1 \
            --outdir {params.outdir} \
            &>{log}
        """


rule process_treetime_output:
    """Process the output of `treetime` to get data suitable for augur."""
    input:
        timetree_w_outgroup=rules.treetime.output.timetree_w_outgroup,
        divtree_w_outgroup=rules.treetime.output.divtree_w_outgroup,
        ancestral_sequences=rules.treetime.output.ancestral_sequences,
        dates=rules.treetime.output.dates,
        site_numbering_map=config["site_numbering_map"],
    output:
        timetree=os.path.join(results_subdir, "timetree.nwk"),
        divtree=os.path.join(results_subdir, "divergence_tree.nwk"),
        brlens=os.path.join(results_subdir, "brlens.json"),
        aa_muts=os.path.join(results_subdir, "aa_muts.json"),
    log:
        os.path.join(log_subdir, "process_treetime_output.txt"),
    conda:
        "environment.yml"
    params:
        no_outgroup=no_outgroup,
        set_branch_lengths_to_n_mutations=set_branch_lengths_to_n_mutations,
    script:
        "scripts/process_treetime_output.py"


rule auspice_config:
    """Build auspice configuration file."""
    input:
        metadata=rules.prep_and_sanitize_data.output.metadata,
        resolved_color_by_metadata=rules.resolve_color_by_metadata.output.resolved,
    output:
        auspice_config=os.path.join(results_subdir, "auspice_config.json"),
    log:
        os.path.join(log_subdir, "auspice_config.txt"),
    conda:
        "environment.yml"
    params:
        display_defaults=config["display_defaults"],
        has_titers=bool(titer_collections),
    script:
        "scripts/auspice_config.py"


rule export:
    """Export the JSON for visualization with `auspice`."""
    input:
        config["addtl_export_args"].get("description", []),
        tree=rules.process_treetime_output.output.divtree,
        brlens=rules.process_treetime_output.output.brlens,
        aa_muts=rules.process_treetime_output.output.aa_muts,
        metadata=rules.prep_and_sanitize_data.output.metadata,
        auspice_config=rules.auspice_config.output.auspice_config,
        export_args=rules.resolve_color_by_metadata.output.export_args,
    output:
        auspice_json=auspice_json,
    log:
        os.path.join(log_subdir, "export.txt"),
    conda:
        "environment.yml"
    params:
        addtl_export_args=" ".join(
            f"--{k} {shlex.quote(v)}" for k, v in config["addtl_export_args"].items()
        ),
    shell:
        # `--metadata-id-columns strain` pins the identifier column: as of augur 34, a
        # metadata column named `id` would otherwise take precedence over `strain`
        """
        augur export v2 \
            --tree {input.tree} \
            --node-data {input.brlens} {input.aa_muts} \
            --include-root-sequence-inline \
            --auspice-config {input.auspice_config} \
            --metadata {input.metadata} \
            --metadata-id-columns strain \
            $(cat {input.export_args}) \
            {params.addtl_export_args} \
            --output {output.auspice_json} \
            &>{log}
        """


if titer_collections:

    rule export_measurements:
        """Export the JSON of titer measurements for one collection."""
        input:
            titers=lambda wc: sanitized_titers[wc.collection],
        output:
            json=os.path.join(results_subdir, "measurements_{collection}.json"),
        log:
            os.path.join(log_subdir, "export_measurements_{collection}.txt"),
        conda:
            "environment.yml"
        params:
            titer_col=lambda wc: titer_collection_d[wc.collection]["titer_col"],
            grouping_columns=lambda wc: titer_collection_d[wc.collection][
                "grouping_columns"
            ],
            # only name the collection when the configuration does, as `augur
            # measurements export` otherwise derives a key from the collection file
            key_arg=lambda wc: (
                f"--key {shlex.quote(str(titer_collection_d[wc.collection]['key']))}"
                if "key" in titer_collection_d[wc.collection]
                else ""
            ),
            addtl_args=lambda wc: " ".join(
                f"--{k} {shlex.quote(v)}"
                for k, v in titer_collection_d[wc.collection]["addtl_args"].items()
            ),
        shell:
            """
            augur measurements export \
                --collection {input.titers} \
                --output-json {output.json} \
                --value-column {params.titer_col} \
                --grouping-column {params.grouping_columns:q} \
                {params.key_arg} \
                {params.addtl_args} \
                &>{log}
            """

    rule measurements_sidecar:
        """Concatenate the collections of measurements into the sidecar JSON."""
        input:
            jsons=expand(
                rules.export_measurements.output.json,
                collection=titer_collection_keys,
            ),
        output:
            auspice_titers_json=auspice_titers_json,
        log:
            os.path.join(log_subdir, "measurements_sidecar.txt"),
        conda:
            "environment.yml"
        params:
            # naming a default is meaningful only when there are several collections to
            # choose among, and a lone unnamed collection is keyed by `augur measurements
            # export` on its file name, which would not match the key named here
            default_collection_arg=(
                f"--default-collection {shlex.quote(default_collection)}"
                if (default_collection and len(titer_collection_keys) > 1)
                else ""
            ),
        shell:
            """
            augur measurements concat \
                --jsons {input.jsons} \
                --output-json {output.auspice_titers_json} \
                {params.default_collection_arg} \
                &>{log}
            """
